### ISSUE TITLE
Move build system into Makefile

### ISSUE THREAD

**Issue by Ste74** [Ste74/org.gnome.desktop-icons-reworked#6]
@dady8889  with this [commit](https://github.com/Ste74/org.gnome.desktop-icons-reworked/commit/b25f576b9767df777b2553d0898766b7bddea78d) i moved the build way into Makefile .. can you check it since all files are build and install correctly but i can't see the extension in tweak-tools.. i presume my typo error but after some research i'm not able to found it.

Thanks in advance
Stefano

**Comment by Ste74** [comment]
Well in my local it fail with this error :
```
lug 04 22:04:27 manjaro org.gnome.Shell.desktop[3692]: == Stack trace for context 0x55a351f18240 ==
lug 04 22:04:27 manjaro org.gnome.Shell.desktop[3692]: #0 0x55a352346a90 i   /usr/share/gnome-shell/extensions/org.gnome-shell.desktop-icons/extension.js:748 (0x7f7bee78fb38 @ 15)
lug 04 22:04:27 manjaro org.gnome.Shell.desktop[3692]: #1 0x7fff01934210 b   self-hosted:251 (0x7f7c105c4ab0 @ 223)
lug 04 22:04:27 manjaro org.gnome.Shell.desktop[3692]: #2 0x55a352346a08 i   /usr/share/gnome-shell/extensions/org.gnome-shell.desktop-icons/extension.js:748 (0x7f7bee78fab0 @ 27)
lug 04 22:04:27 manjaro org.gnome.Shell.desktop[3692]: #3 0x7fff01934f40 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f7c105b5de0 @ 71)
lug 04 22:04:27 manjaro org.gnome.Shell.desktop[3692]: #4 0x55a352346968 i   /usr/share/gnome-shell/extensions/org.gnome-shell.desktop-icons/extension.js:737 (0x7f7bee78f9a0 @ 17)

```
Any idea ?

**Comment by dady8889** [comment]
Yeah, so it didn't work because you put version 0.3.2 in the metadata, but you can have only one . in the version.

**Comment by Ste74** [comment]
Thank you .. Js is not my friend.. really version array into metadata want only one dot ? Funny i lost my mind for two days :smile: .. ok build for manjaro and pkgbuild for AUR is in progress.. BTW what distro. you use ?

**Comment by dady8889** [comment]
@Ste74 No problem. Sorry don't know what S.O. means.

**Comment by Ste74** [comment]
I have corrected my question.. What distribution you use? :wink:

**Comment by dady8889** [comment]
@Ste74 Oh right, I use arch linux x64 with gnome 3 wayland.

**Comment by Ste74** [comment]
Great

**Comment by Ste74** [comment]
In the Aur just now
